spring.application.name=vigi-gate

# Konfigurasi Koneksi PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/vg_db
spring.datasource.username=postgres
spring.datasource.password=smaroe87

# Pengaturan Hibernate JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# API Key Gemini Resmi
gemini.api.key=AIzaSyA67_C_i3E5BQVXmrMswdmixFUIQTzzSHY