spring.datasource.url=jdbc:postgresql://localhost:5432/vigi_gate
spring.datasource.username=postgres
spring.datasource.password=smaroe87
spring.jpa.hibernate.ddl-auto=update

spring.ai.google.gemini.api-key=AIzaSyAs9AcLFfiREpjoJV5EL8ttazt7A7r1QcQ